/* eslint-env node */
/* eslint-disable no-magic-numbers */
module.exports = {
  "extends": "eslint:recommended",
  "parserOptions": {
    "ecmaVersion": 5
  },
  "rules": {
    "array-callback-return": "error",
    "block-scoped-var": "error",
    "callback-return": ["error", ["callback", "cb", "next", "done"]],
    "camelcase": "off",
    "comma-dangle": "off",
    "comma-spacing": "error",
    "complexity": ["error", { "max": 20 }],
    "consistent-return": "error",
    "curly": ["error", "multi-line", "consistent"],
    "dot-location": ["error", "property"],
    "eol-last": "error",
    "eqeqeq": "off",
    "handle-callback-err": ["error", "^err"],
    "indent": ["error", 2, { "SwitchCase": 1 }],
    "key-spacing": ["error", { "beforeColon": false, "afterColon": true }],
    "keyword-spacing": "error",
    "max-depth": ["error", 5],
    "max-len": ["error", 80, 4],
    "max-statements-per-line": ["error", { "max": 1 }],
    "new-cap": "off",
    "new-parens": "error",
    "no-alert": "error",
    "no-array-constructor": "error",
    "no-caller": "error",
    "no-catch-shadow": "error",
    "no-empty-function": "error",
    "no-else-return": "error",
    "no-eval": "error",
    "no-extend-native": "error",
    "no-extra-bind": "error",
    "no-floating-decimal": "error",
    "no-implicit-coercion": "error",
    "no-implicit-globals": "error",
    "no-implied-eval": "error",
    "no-iterator": "error",
    "no-label-var": "error",
    "no-labels": "error",
    "no-lone-blocks": "error",
    "no-lonely-if": "error",
    "no-loop-func": "error",
    "no-magic-numbers": "error",
    "no-mixed-requires": ["error", { "allowCall": true }],
    "no-multi-spaces": "error",
    "no-multi-str": "error",
    "no-native-reassign": "error",
    "no-new": "error",
    "no-new-func": "error",
    "no-new-object": "error",
    "no-new-wrappers": "error",
    "no-octal-escape": "error",
    "no-path-concat": "error",
    "no-process-env": "error", // opt-in per function if needed
    "no-process-exit": "error", // opt-in per function if needed
    "no-proto": "error",
    "no-return-assign": "error",
    "no-script-url": "error",
    "no-self-compare": "error",
    "no-sequences": "error",
    "no-shadow": "error",
    "no-shadow-restricted-names": "error",
    "no-spaced-func": "error",
    "no-throw-literal": "error",
    "no-trailing-spaces": "error",
    "no-undef-init": "error",
    "no-underscore-dangle": "error",
    "no-unmodified-loop-condition": "error",
    "no-unused-expressions": "error",
    "no-unused-vars": ["error", "all"],
    "no-use-before-define": ["error", "nofunc"],
    "no-useless-call": "error",
    "no-useless-concat": "error",
    "no-useless-escape": "error",
    "no-with": "error",
    "quotes": "off",
    "semi": "error",
    "semi-spacing": ["error", {"before": false, "after": true}],
    "space-infix-ops": "error",
    "space-unary-ops": ["error", { "words": true, "nonwords": false }],
    "strict": "off",
    "yoda": ["error", "never"],
  }
};
