/* eslint-env node */
module.exports = {
    "extends": "eslint:recommended",
    "parserOptions": {
        "ecmaVersion": 5
    },
    "rules": {
        "camelcase": "off",
        "comma-dangle": "off",
        "comma-spacing": "error",
        "consistent-return": "error",
        "curly": ["error", "multi-line"],
        "dot-notation": ["error", { "allowKeywords": true }],
        "eol-last": "error",
        "eqeqeq": "off",
        "handle-callback-err": ["error", "^err"],
        "key-spacing": ["error", { "beforeColon": false, "afterColon": true }],
        "keyword-spacing": "error",
        "max-depth": ["error", 5],
        "max-len": ["error", 80, 4],
        "new-cap": "off",
        "new-parens": "error",
        "no-alert": "error",
        "no-array-constructor": "error",
        "no-caller": "error",
        "no-catch-shadow": "error",
        "no-console": "error", // opt-in per file if needed
        "no-else-return": "error",
        "no-eq-null": "error",
        "no-eval": "error",
        "no-extend-native": "error",
        "no-extra-bind": "error",
        "no-extra-parens": ["error", "functions"],
        "no-implied-eval": "error",
        "no-iterator": "error",
        "no-label-var": "error",
        "no-labels": "error",
        "no-lone-blocks": "error",
        "no-lonely-if": "error",
        "no-loop-func": "error",
        "no-mixed-requires": ["error", true],
        "no-multi-spaces": "error",
        "no-multi-str": "error",
        "no-native-reassign": "error",
        "no-new": "error",
        "no-new-func": "error",
        "no-new-object": "error",
        "no-new-wrappers": "error",
        "no-octal-escape": "error",
        "no-path-concat": "off",
        "no-process-exit": "error", // opt-in per file if needed
        "no-proto": "error",
        "no-return-assign": "error",
        "no-script-url": "error",
        "no-sequences": "error",
        "no-shadow": "error",
        "no-shadow-restricted-names": "error",
        "no-spaced-func": "error",
        "no-trailing-spaces": "error",
        "no-undef-init": "error",
        "no-underscore-dangle": "error",
        "no-unused-expressions": "error",
        "no-unused-vars": ["error", "all"],
        "no-use-before-define": ["error", "nofunc"],
        "no-with": "error",
        "quotes": "off",
        "semi": "error",
        "semi-spacing": ["error", {"before": false, "after": true}],
        "space-infix-ops": "error",
        "space-unary-ops": ["error", { "words": true, "nonwords": false }],
        "strict": "off",
        "yoda": ["error", "never"],
    }
};
